import type { CategoryId, TalkiCategory } from '../types';
import { art } from './art';

/**
 * Ported verbatim from index.html 1480-1592 (CATEGORIES). Generated from
 * docs/migration/fixtures/legacy-domain.json, which is itself extracted
 * (not hand-copied) from index.html by tools/extract-legacy-domain.mjs — see
 * that file and apps/mobile/tests/unit/domain-parity.test.ts, which asserts
 * this object deep-equals the fixture on every test run.
 *
 * 182 words across 10 categories: animals 26, food 26, colors 26, home 26,
 * outside 18, actions 16, family 12, body 12, numbers 10, emotions 10.
 */
export const CATEGORIES: Record<Exclude<CategoryId, 'mine'>, TalkiCategory> = {
  animals: {
    id: "animals",
    title: "חיות",
    icon: "🐶",
    cls: "c-animals",
    items: [
      { word: "כֶּלֶב", emoji: "🐶", sound: "הַב הַב", img: art("animals", "dog"), shape: "quadruped" },
      { word: "חָתוּל", emoji: "🐱", sound: "מְיָאוּ", img: art("animals", "cat"), shape: "quadruped" },
      { word: "פָּרָה", emoji: "🐮", sound: "מוּ", img: art("animals", "cow"), shape: "quadruped" },
      { word: "אַרְיֵה", emoji: "🦁", sound: "רְרְרָאוּ", img: art("animals", "lion"), shape: "quadruped" },
      { word: "פִּיל", emoji: "🐘", img: art("animals", "elephant"), shape: "quadruped" },
      { word: "בַּרְוָוז", emoji: "🦆", sound: "גַּע גַּע", img: art("animals", "duck"), shape: "flying-animal" },
      { word: "סוּס", emoji: "🐎", sound: "הִי הָה", img: art("animals", "horse"), shape: "quadruped" },
      { word: "תַּרְנְגוֹלֶת", emoji: "🐔", sound: "קוּ קוּ רִיקוּ", img: art("animals", "hen"), shape: "flying-animal" },
      { word: "כִּבְשָׂה", emoji: "🐑", sound: "מֶה", img: art("animals", "sheep"), shape: "quadruped" },
      { word: "קוֹף", emoji: "🐒", sound: "אוּ אוּ אָה אָה", img: art("animals", "monkey"), shape: "quadruped" },
      { word: "חֲזִיר", emoji: "🐷", sound: "אוֹיְנְק", img: art("animals", "pig"), shape: "quadruped" },
      { word: "צְפַרְדֵּעַ", emoji: "🐸", sound: "קְוָואק", img: art("animals", "frog"), shape: "small-animal" },
      { word: "פַּרְפַּר", emoji: "🦋", img: art("animals", "butterfly"), shape: "small-animal" },
      { word: "אַרְנָב", emoji: "🐰", img: art("animals", "rabbit"), shape: "small-animal" },
      { word: "צָב", emoji: "🐢", img: art("animals", "turtle"), shape: "small-animal" },
      { word: "דָּג", emoji: "🐟", img: art("animals", "fish"), shape: "small-animal" },
      { word: "צִפּוֹר", emoji: "🐦", sound: "צִיוּ צִיוּ", img: art("animals", "bird"), shape: "flying-animal" },
      { word: "דֹּב", emoji: "🐻", sound: "גְּרְרְר", img: art("animals", "bear"), shape: "quadruped" },
      { word: "גִּ'ירָפָה", emoji: "🦒", img: art("animals", "giraffe"), shape: "quadruped" },
      { word: "נָחָשׁ", emoji: "🐍", sound: "שְׁשְׁשְׁ", img: art("animals", "snake"), shape: "small-animal" },
      { word: "עַכְבָּר", emoji: "🐭", sound: "צִיק צִיק", img: art("animals", "mouse"), shape: "small-animal" },
      { word: "זֶבְּרָה", emoji: "🦓", img: art("animals", "zebra"), shape: "quadruped" },
      { word: "יַנְשׁוּף", emoji: "🦉", sound: "הוּ הוּ", img: art("animals", "owl"), shape: "flying-animal" },
      { word: "דְּבוֹרָה", emoji: "🐝", sound: "זְזְזְז", img: art("animals", "bee"), shape: "small-animal" },
      { word: "נְמָלָה", emoji: "🐜", img: art("animals", "ant"), shape: "small-animal" },
      { word: "פִּינְגְּוִין", emoji: "🐧", img: art("animals", "penguin"), shape: "flying-animal" },
    ],
  },
  food: {
    id: "food",
    title: "אוֹכֶל",
    icon: "🍎",
    cls: "c-food",
    items: [
      { word: "תַּפּוּחַ", emoji: "🍎", img: art("food", "apple"), shape: "fruit" },
      { word: "בָּנָנָה", emoji: "🍌", img: art("food", "banana"), shape: "fruit" },
      { word: "מַיִם", emoji: "💧", img: art("food", "water"), shape: "food-drink" },
      { word: "לֶחֶם", emoji: "🍞", img: art("food", "bread"), shape: "dairy-bread" },
      { word: "גְּלִידָה", emoji: "🍦", img: art("food", "ice-cream"), shape: "frozen-food" },
      { word: "עַגְבָנִיָּה", emoji: "🍅", img: art("food", "tomato"), shape: "vegetable" },
      { word: "מְלָפְפוֹן", emoji: "🥒", img: art("food", "cucumber"), shape: "vegetable" },
      { word: "חָלָב", emoji: "🥛", img: art("food", "milk"), shape: "food-drink" },
      { word: "עֲנָבִים", emoji: "🍇", img: art("food", "grapes"), shape: "fruit" },
      { word: "תּוּת", emoji: "🍓", img: art("food", "strawberry"), shape: "fruit" },
      { word: "תַּפּוּז", emoji: "🍊", img: art("food", "orange"), shape: "fruit" },
      { word: "אֲבַטִּיחַ", emoji: "🍉", img: art("food", "watermelon"), shape: "fruit" },
      { word: "בֵּיצָה", emoji: "🥚", img: art("food", "egg"), shape: "dairy-bread" },
      { word: "גְּבִינָה", emoji: "🧀", img: art("food", "cheese"), shape: "dairy-bread" },
      { word: "עוֹף", emoji: "🍗", img: art("food", "chicken"), shape: "prepared-food" },
      { word: "פִּצָּה", emoji: "🍕", img: art("food", "pizza"), shape: "prepared-food" },
      { word: "מָרָק", emoji: "🥣", img: art("food", "soup"), shape: "food-drink" },
      { word: "עוּגָה", emoji: "🍰", img: art("food", "cake"), shape: "prepared-food" },
      { word: "עוּגִיָּה", emoji: "🍪", img: art("food", "cookie"), shape: "prepared-food" },
      { word: "מִיץ", emoji: "🧃", img: art("food", "juice"), shape: "food-drink" },
      { word: "כָּרִיךְ", emoji: "🥪", img: art("food", "sandwich"), shape: "prepared-food" },
      { word: "פּוֹפְּקוֹרְן", emoji: "🍿", img: art("food", "popcorn"), shape: "prepared-food" },
      { word: "שׁוֹקוֹלָד", emoji: "🍫", img: art("food", "chocolate"), shape: "prepared-food" },
      { word: "גֶּזֶר", emoji: "🥕", img: art("food", "carrot"), shape: "vegetable" },
      { word: "תִּירָס", emoji: "🌽", img: art("food", "corn"), shape: "vegetable" },
      { word: "לִימוֹן", emoji: "🍋", img: art("food", "lemon"), shape: "fruit" },
    ],
  },
  colors: {
    id: "colors",
    title: "צְבָעִים וְצוּרוֹת",
    icon: "🎨",
    cls: "c-colors",
    items: [
      { word: "אָדוֹם", emoji: "🔴", img: art("colors", "red"), shape: "color" },
      { word: "כָּחוֹל", emoji: "🔵", img: art("colors", "blue"), shape: "color" },
      { word: "צָהוֹב", emoji: "🟡", img: art("colors", "yellow"), shape: "color" },
      { word: "יָרוֹק", emoji: "🟢", img: art("colors", "green"), shape: "color" },
      { word: "כָּתוֹם", emoji: "🟠", img: art("colors", "orange"), shape: "color" },
      { word: "סָגוֹל", emoji: "🟣", img: art("colors", "purple"), shape: "color" },
      { word: "וָרוֹד", emoji: "🩷", img: art("colors", "pink"), shape: "color" },
      { word: "חוּם", emoji: "🤎", img: art("colors", "brown"), shape: "color" },
      { word: "שָׁחוֹר", emoji: "🖤", img: art("colors", "black"), shape: "color" },
      { word: "לָבָן", emoji: "🤍", img: art("colors", "white"), shape: "color" },
      { word: "אָפוֹר", emoji: "🩶", img: art("colors", "gray"), shape: "color" },
      { word: "תְּכֵלֶת", emoji: "🩵", img: art("colors", "light-blue"), shape: "color" },
      { word: "צִבְעוֹנִי", emoji: "🌈", img: art("colors", "colorful"), shape: "color" },
      { word: "כּוֹכָב", emoji: "⭐", img: art("colors", "star"), shape: "shape-object" },
      { word: "לֵב", emoji: "❤️", img: art("colors", "heart"), shape: "shape-object" },
      { word: "עִיגּוּל", emoji: "⭕", img: art("colors", "circle"), shape: "shape-object" },
      { word: "רִיבּוּעַ", emoji: "🟦", img: art("colors", "square"), shape: "shape-object" },
      { word: "מְשׁוּלָּשׁ", emoji: "🔺", img: art("colors", "triangle"), shape: "shape-object" },
      { word: "מְעוּיָּן", emoji: "🔸", img: art("colors", "diamond"), shape: "shape-object" },
      { word: "חֵץ", emoji: "➡️", img: art("colors", "arrow"), shape: "shape-object" },
      { word: "יָרֵחַ", emoji: "🌙", img: art("colors", "moon"), shape: "nature-symbol" },
      { word: "טִפָּה", emoji: "💧", img: art("colors", "drop"), shape: "nature-symbol" },
      { word: "פֶּרַח", emoji: "🌸", img: art("colors", "flower"), shape: "nature-symbol" },
      { word: "תִּלְתָּן", emoji: "☘️", img: art("colors", "clover"), shape: "nature-symbol" },
      { word: "כֶּתֶר", emoji: "👑", img: art("colors", "crown"), shape: "nature-symbol" },
      { word: "בָּלוֹן", emoji: "🎈", img: art("colors", "balloon"), shape: "nature-symbol" },
    ],
  },
  home: {
    id: "home",
    title: "בַּבַּיִת",
    icon: "🧸",
    cls: "c-home",
    items: [
      { word: "כַּדּוּר", emoji: "⚽", img: art("home", "ball"), shape: "toy" },
      { word: "בּוּבָּה", emoji: "🧸", img: art("home", "doll"), shape: "toy" },
      { word: "מִיטָה", emoji: "🛏️", img: art("home", "bed"), shape: "furniture" },
      { word: "נַעֲלַיִם", emoji: "👟", img: art("home", "shoes"), shape: "clothing" },
      { word: "מוֹצֵץ", emoji: "🍼", img: art("home", "pacifier"), shape: "toy" },
      { word: "סֵפֶר", emoji: "📖", img: art("home", "book"), shape: "media" },
      { word: "כִּסֵּא", emoji: "🪑", img: art("home", "chair"), shape: "furniture" },
      { word: "סַפָּה", emoji: "🛋️", img: art("home", "sofa"), shape: "furniture" },
      { word: "טֶלֶוִיזְיָה", emoji: "📺", img: art("home", "television"), shape: "electronics" },
      { word: "דֶּלֶת", emoji: "🚪", img: art("home", "door"), shape: "building-part" },
      { word: "חַלּוֹן", emoji: "🪟", img: art("home", "window"), shape: "building-part" },
      { word: "שְׂמִיכָה", emoji: "🛌", img: art("home", "blanket"), shape: "textile" },
      { word: "אַמְבַּטְיָה", emoji: "🛁", img: art("home", "bathtub"), shape: "fixture" },
      { word: "מִבְרֶשֶׁת שִׁנַּיִם", emoji: "🪥", img: art("home", "toothbrush"), shape: "hygiene" },
      { word: "סַבּוֹן", emoji: "🧼", img: art("home", "soap"), shape: "hygiene" },
      { word: "שֵׁירוּתִים", emoji: "🚽", img: art("home", "toilet"), shape: "fixture" },
      { word: "צַלַּחַת", emoji: "🍽️", img: art("home", "plate"), shape: "dishware" },
      { word: "כּוֹס", emoji: "🥤", img: art("home", "cup"), shape: "dishware" },
      { word: "כַּף", emoji: "🥄", img: art("home", "spoon"), shape: "dishware" },
      { word: "שָׁעוֹן", emoji: "⏰", img: art("home", "clock"), shape: "object" },
      { word: "טֶלֶפוֹן", emoji: "📱", img: art("home", "phone"), shape: "electronics" },
      { word: "מַפְתֵּחַ", emoji: "🔑", img: art("home", "key"), shape: "object" },
      { word: "מַשְׁקָפַיִם", emoji: "👓", img: art("home", "glasses"), shape: "accessory" },
      { word: "מִטְרִיָּה", emoji: "☂️", img: art("home", "umbrella"), shape: "accessory" },
      { word: "בְּגָדִים", emoji: "👕", img: art("home", "clothes"), shape: "clothing" },
      { word: "גַּרְבַּיִם", emoji: "🧦", img: art("home", "socks"), shape: "clothing" },
    ],
  },
  family: {
    id: "family",
    title: "מִשְׁפָּחָה",
    icon: "👨‍👩‍👧",
    cls: "c-family",
    items: [
      { word: "אִמָּא", emoji: "👩", img: art("family", "mom"), shape: "family-member" },
      { word: "אַבָּא", emoji: "👨", img: art("family", "dad"), shape: "family-member" },
      { word: "סַבְתָּא", emoji: "👵", img: art("family", "grandma"), shape: "family-member" },
      { word: "סַבָּא", emoji: "👴", img: art("family", "grandpa"), shape: "family-member" },
      { word: "תִּינוֹק", emoji: "👶", img: art("family", "baby"), shape: "family-member" },
      { word: "אָח", emoji: "👦", img: art("family", "brother"), shape: "family-member" },
      { word: "אָחוֹת", emoji: "👧", img: art("family", "sister"), shape: "family-member" },
      { word: "יַלְדָּה", emoji: "🧒", img: art("family", "girl"), shape: "family-member" },
      { word: "דּוֹדָה", emoji: "💃", img: art("family", "aunt"), shape: "family-member" },
      { word: "דּוֹד", emoji: "🕺", img: art("family", "uncle"), shape: "family-member" },
      { word: "חָבֵר", emoji: "🧑‍🤝‍🧑", img: art("family", "friend"), shape: "family-member" },
      { word: "מִשְׁפָּחָה", emoji: "👨‍👩‍👧‍👦", img: art("family", "family"), shape: "family-member" },
    ],
  },
  body: {
    id: "body",
    title: "הַגּוּף",
    icon: "👀",
    cls: "c-body",
    items: [
      { word: "עַיִן", emoji: "👁️", img: art("body", "eye"), shape: "body" },
      { word: "אֹזֶן", emoji: "👂", img: art("body", "ear"), shape: "body" },
      { word: "אַף", emoji: "👃", img: art("body", "nose"), shape: "body" },
      { word: "פֶּה", emoji: "👄", img: art("body", "mouth"), shape: "body" },
      { word: "יָד", emoji: "✋", img: art("body", "hand"), shape: "body" },
      { word: "רֶגֶל", emoji: "🦶", img: art("body", "foot"), shape: "body" },
      { word: "אֶצְבַּע", emoji: "☝️", img: art("body", "finger"), shape: "body" },
      { word: "שֵׁן", emoji: "🦷", img: art("body", "tooth"), shape: "body" },
      { word: "לָשׁוֹן", emoji: "👅", img: art("body", "tongue"), shape: "body" },
      { word: "שֵׂעָר", emoji: "💇", img: art("body", "hair"), shape: "body" },
      { word: "לֵב", emoji: "🫀", img: art("body", "heart"), shape: "body" },
      { word: "בֶּרֶךְ", emoji: "🦵", img: art("body", "knee"), shape: "body" },
    ],
  },
  actions: {
    id: "actions",
    title: "פְּעוּלוֹת",
    icon: "🏃",
    cls: "c-actions",
    items: [
      { word: "אוֹכֶלֶת", emoji: "🍽️", img: art("actions", "eating"), shape: "action" },
      { word: "שׁוֹתָה", emoji: "🥤", img: art("actions", "drinking"), shape: "action" },
      { word: "יְשֵׁנָה", emoji: "😴", img: art("actions", "sleeping"), shape: "action" },
      { word: "רָצָה", emoji: "🏃", img: art("actions", "running"), shape: "action" },
      { word: "קוֹפֶצֶת", emoji: "🤸", img: art("actions", "jumping"), shape: "action" },
      { word: "מוֹחֵאת כַּפַּיִם", emoji: "👏", img: art("actions", "clapping"), shape: "action" },
      { word: "מְנַשֶּׁקֶת", emoji: "😘", img: art("actions", "kissing"), shape: "action" },
      { word: "מְחַבֶּקֶת", emoji: "🤗", img: art("actions", "hugging"), shape: "action" },
      { word: "בּוֹכָה", emoji: "😢", img: art("actions", "crying"), shape: "action" },
      { word: "צוֹחֶקֶת", emoji: "😂", img: art("actions", "laughing"), shape: "action" },
      { word: "מִתְרַחֶצֶת", emoji: "🛁", img: art("actions", "bathing"), shape: "action" },
      { word: "שָׁרָה", emoji: "🎤", img: art("actions", "singing"), shape: "action" },
      { word: "מְצַיֶּרֶת", emoji: "🎨", img: art("actions", "drawing"), shape: "action" },
      { word: "הוֹלֶכֶת", emoji: "🚶", img: art("actions", "walking"), shape: "action" },
      { word: "שׂוֹחָה", emoji: "🏊", img: art("actions", "swimming"), shape: "action" },
      { word: "רוֹקֶדֶת", emoji: "💃", img: art("actions", "dancing"), shape: "action" },
    ],
  },
  numbers: {
    id: "numbers",
    title: "מִסְפָּרִים",
    icon: "🔢",
    cls: "c-numbers",
    items: [
      { word: "אַחַת", emoji: "1️⃣", img: art("numbers", "one"), shape: "number" },
      { word: "שְׁתַּיִם", emoji: "2️⃣", img: art("numbers", "two"), shape: "number" },
      { word: "שָׁלוֹשׁ", emoji: "3️⃣", img: art("numbers", "three"), shape: "number" },
      { word: "אַרְבַּע", emoji: "4️⃣", img: art("numbers", "four"), shape: "number" },
      { word: "חָמֵשׁ", emoji: "5️⃣", img: art("numbers", "five"), shape: "number" },
      { word: "שֵׁשׁ", emoji: "6️⃣", img: art("numbers", "six"), shape: "number" },
      { word: "שֶׁבַע", emoji: "7️⃣", img: art("numbers", "seven"), shape: "number" },
      { word: "שְׁמוֹנֶה", emoji: "8️⃣", img: art("numbers", "eight"), shape: "number" },
      { word: "תֵּשַׁע", emoji: "9️⃣", img: art("numbers", "nine"), shape: "number" },
      { word: "עֶשֶׂר", emoji: "🔟", img: art("numbers", "ten"), shape: "number" },
    ],
  },
  outside: {
    id: "outside",
    title: "בַּחוּץ",
    icon: "🌳",
    cls: "c-outside",
    items: [
      { word: "עֵץ", emoji: "🌳", img: art("outside", "tree"), shape: "nature-plant" },
      { word: "שֶׁמֶשׁ", emoji: "☀️", img: art("outside", "sun"), shape: "nature-weather" },
      { word: "עָנָן", emoji: "☁️", img: art("outside", "cloud"), shape: "nature-weather" },
      { word: "גֶּשֶׁם", emoji: "🌧️", img: art("outside", "rain"), shape: "nature-weather" },
      { word: "שֶׁלֶג", emoji: "❄️", img: art("outside", "snow"), shape: "nature-weather" },
      { word: "מְכוֹנִית", emoji: "🚗", img: art("outside", "car"), shape: "vehicle" },
      { word: "אוֹטוֹבּוּס", emoji: "🚌", img: art("outside", "bus"), shape: "vehicle" },
      { word: "אוֹפַנַּיִם", emoji: "🚲", img: art("outside", "bicycle"), shape: "vehicle" },
      { word: "מָטוֹס", emoji: "✈️", img: art("outside", "airplane"), shape: "vehicle" },
      { word: "סִירָה", emoji: "⛵", img: art("outside", "boat"), shape: "vehicle" },
      { word: "רַכֶּבֶת", emoji: "🚂", img: art("outside", "train"), shape: "vehicle" },
      { word: "בַּיִת", emoji: "🏠", img: art("outside", "house"), shape: "building" },
      { word: "גַּן שַׁעֲשׁוּעִים", emoji: "🎠", img: art("outside", "playground"), shape: "building" },
      { word: "יָם", emoji: "🌊", img: art("outside", "sea"), shape: "nature-water" },
      { word: "חוֹל", emoji: "🏖️", img: art("outside", "sand"), shape: "nature-water" },
      { word: "דֶּשֶׁא", emoji: "🌿", img: art("outside", "grass"), shape: "nature-plant" },
      { word: "צֶמַח", emoji: "🌷", img: art("outside", "plant"), shape: "nature-plant" },
      { word: "כּוֹכָבִים", emoji: "🌟", img: art("outside", "stars"), shape: "nature-weather" },
    ],
  },
  emotions: {
    id: "emotions",
    title: "רְגָשׁוֹת",
    icon: "😊",
    cls: "c-emotions",
    items: [
      { word: "שְׂמֵחָה", emoji: "😊", img: art("emotions", "happy"), shape: "emotion" },
      { word: "עֲצוּבָה", emoji: "😢", img: art("emotions", "sad"), shape: "emotion" },
      { word: "כּוֹעֶסֶת", emoji: "😠", img: art("emotions", "angry"), shape: "emotion" },
      { word: "מְפֻחֶדֶת", emoji: "😨", img: art("emotions", "scared"), shape: "emotion" },
      { word: "עֲיֵפָה", emoji: "🥱", img: art("emotions", "tired"), shape: "emotion" },
      { word: "מֻפְתַּעַת", emoji: "😲", img: art("emotions", "surprised"), shape: "emotion" },
      { word: "אוֹהֶבֶת", emoji: "🥰", img: art("emotions", "loving"), shape: "emotion" },
      { word: "מִתְבַּיֶּשֶׁת", emoji: "🙈", img: art("emotions", "shy"), shape: "emotion" },
      { word: "רְעֵבָה", emoji: "😋", img: art("emotions", "hungry"), shape: "emotion" },
      { word: "מִשְׁתַּעֲמֶמֶת", emoji: "😑", img: art("emotions", "bored"), shape: "emotion" },
    ],
  },
};
