import { AUDIO_ASSETS } from '../../data/assets/audio.generated';

/**
 * `audioPolicy.ts`'s `MUSIC_FILES`/`SFX_FILES` values ('music/01_....mp3',
 * 'sfx/01_....mp3') are legacy-relative paths, not bundler module ids.
 * `AUDIO_ASSETS` (generated by tools/generate-mobile-asset-registry.mjs from
 * the real files under assets/audio/) is the one place that turns one into
 * the other, so neither engine adapter hand-rolls its own path-to-`require`
 * mapping — see phase-04-plan.md, "no component ever learns an MP3
 * filename": a policy string never becomes a raw path anywhere outside this
 * function.
 */
export function assetModuleFor(policyFile: string): number {
  const mod = AUDIO_ASSETS[policyFile];
  if (mod == null) {
    throw new Error(`No bundled asset registered for audio policy file "${policyFile}"`);
  }
  return mod;
}
