/**
 * GENERATED by tools/generate-mobile-asset-registry.mjs. Do not hand-edit —
 * re-run the generator instead (it is deterministic; two runs are
 * byte-identical). Keys deliberately match audioPolicy.ts's
 * MUSIC_FILES/SFX_FILES value format ('music/...', 'sfx/...'), not a full
 * assets/audio/ path, so resolveMusicFile()/SFX_FILES lookups key into this
 * registry unchanged. assets/audio/audio-logic.js (pure logic, not an
 * asset) is excluded.
 */

export const AUDIO_ASSETS: Record<string, number> = {
  "music/01_main_menu_welcome.mp3": require("../../../../../assets/audio/music/01_main_menu_welcome.mp3"),
  "music/02_gameplay_bouncy.mp3": require("../../../../../assets/audio/music/02_gameplay_bouncy.mp3"),
  "music/03_gameplay_curious.mp3": require("../../../../../assets/audio/music/03_gameplay_curious.mp3"),
  "music/04_gameplay_gentle.mp3": require("../../../../../assets/audio/music/04_gameplay_gentle.mp3"),
  "music/05_listening_focus.mp3": require("../../../../../assets/audio/music/05_listening_focus.mp3"),
  "music/06_talki_playroom.mp3": require("../../../../../assets/audio/music/06_talki_playroom.mp3"),
  "music/07_talki_playroom_b.mp3": require("../../../../../assets/audio/music/07_talki_playroom_b.mp3"),
  "music/08_little_discoveries_a.mp3": require("../../../../../assets/audio/music/08_little_discoveries_a.mp3"),
  "music/09_little_discoveries_b.mp3": require("../../../../../assets/audio/music/09_little_discoveries_b.mp3"),
  "music/10_sunny_card_parade_a.mp3": require("../../../../../assets/audio/music/10_sunny_card_parade_a.mp3"),
  "music/11_sunny_card_parade_b.mp3": require("../../../../../assets/audio/music/11_sunny_card_parade_b.mp3"),
  "music/12_warm_card_carousel_a.mp3": require("../../../../../assets/audio/music/12_warm_card_carousel_a.mp3"),
  "music/13_warm_card_carousel_b.mp3": require("../../../../../assets/audio/music/13_warm_card_carousel_b.mp3"),
  "sfx/01_ui_tap.mp3": require("../../../../../assets/audio/sfx/01_ui_tap.mp3"),
  "sfx/02_ui_soft_tap.mp3": require("../../../../../assets/audio/sfx/02_ui_soft_tap.mp3"),
  "sfx/03_ui_pop.mp3": require("../../../../../assets/audio/sfx/03_ui_pop.mp3"),
  "sfx/04_ui_back_close.mp3": require("../../../../../assets/audio/sfx/04_ui_back_close.mp3"),
  "sfx/05_ui_swipe_whoosh.mp3": require("../../../../../assets/audio/sfx/05_ui_swipe_whoosh.mp3"),
  "sfx/06_drag_pickup.mp3": require("../../../../../assets/audio/sfx/06_drag_pickup.mp3"),
  "sfx/07_drag_drop_place.mp3": require("../../../../../assets/audio/sfx/07_drag_drop_place.mp3"),
  "sfx/08_correct_answer.mp3": require("../../../../../assets/audio/sfx/08_correct_answer.mp3"),
  "sfx/09_try_again_gentle.mp3": require("../../../../../assets/audio/sfx/09_try_again_gentle.mp3"),
  "sfx/10_star_collect.mp3": require("../../../../../assets/audio/sfx/10_star_collect.mp3"),
  "sfx/11_reward_unlock.mp3": require("../../../../../assets/audio/sfx/11_reward_unlock.mp3"),
  "sfx/12_confetti_burst.mp3": require("../../../../../assets/audio/sfx/12_confetti_burst.mp3"),
  "sfx/13_level_start.mp3": require("../../../../../assets/audio/sfx/13_level_start.mp3"),
  "sfx/14_level_complete.mp3": require("../../../../../assets/audio/sfx/14_level_complete.mp3"),
  "sfx/15_countdown_tick.mp3": require("../../../../../assets/audio/sfx/15_countdown_tick.mp3"),
  "sfx/16_countdown_go.mp3": require("../../../../../assets/audio/sfx/16_countdown_go.mp3"),
  "sfx/17_notification_soft.mp3": require("../../../../../assets/audio/sfx/17_notification_soft.mp3"),
  "sfx/18_listening_ready.mp3": require("../../../../../assets/audio/sfx/18_listening_ready.mp3"),
  "sfx/19_voice_heard_success.mp3": require("../../../../../assets/audio/sfx/19_voice_heard_success.mp3"),
  "sfx/20_voice_finished.mp3": require("../../../../../assets/audio/sfx/20_voice_finished.mp3"),
  "sfx/21_match_snap.mp3": require("../../../../../assets/audio/sfx/21_match_snap.mp3"),
  "sfx/22_invalid_move_soft.mp3": require("../../../../../assets/audio/sfx/22_invalid_move_soft.mp3"),
};
